// Copyright (C) 2026 Pumpkin-MC Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::market::ExternalPluginMetadata;

pub const LOCKFILE_NAME: &str = ".ppm.lock";
pub const LOCKFILE_FALLBACK: &str = "ppm.lock";

/// Lockfile tracking marketplace plugins installed via ppm.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Lockfile {
    pub version: u32,
    #[serde(default)]
    pub plugins: BTreeMap<String, LockedPlugin>,
}

impl Default for Lockfile {
    fn default() -> Self {
        Self {
            version: 1,
            plugins: BTreeMap::new(),
        }
    }
}

/// Metadata recorded in .ppm.lock for a marketplace plugin.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedPlugin {
    /// Marketplace plugin database ID
    pub id: i64,
    /// Unique public ID (e.g. S1zisQxa)
    pub public_id: String,
    /// Plugin name
    pub name: String,
    /// Author / developer username
    pub author: String,
    /// Installed version (if specified by marketplace)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Filename on disk (e.g. AppleSkin.wasm)
    pub file: String,
    /// Timestamp when installed or updated
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl Lockfile {
    pub fn new() -> Self {
        Self::default()
    }

    /// Load lockfile from the plugins directory.
    pub fn load_from_dir(plugins_dir: &Path) -> Result<Self> {
        let path = Self::locate(plugins_dir);
        if !path.exists() {
            return Ok(Self::new());
        }
        let content = fs::read_to_string(&path)
            .with_context(|| format!("Failed to read lockfile at '{}'", path.display()))?;
        let lockfile: Self = toml::from_str(&content)
            .with_context(|| format!("Failed to parse lockfile at '{}'", path.display()))?;
        Ok(lockfile)
    }

    /// Save lockfile to the plugins directory.
    pub fn save_to_dir(&self, plugins_dir: &Path) -> Result<PathBuf> {
        if !plugins_dir.exists() {
            fs::create_dir_all(plugins_dir).with_context(|| {
                format!(
                    "Failed to create plugins directory at '{}'",
                    plugins_dir.display()
                )
            })?;
        }
        let path = Self::locate(plugins_dir);
        let header = "# Auto-generated by Pumpkin Package Manager (ppm). Do not edit manually.\n\n";
        let toml_str =
            toml::to_string_pretty(self).context("Failed to serialize lockfile to TOML")?;
        fs::write(&path, format!("{header}{toml_str}"))
            .with_context(|| format!("Failed to write lockfile to '{}'", path.display()))?;
        Ok(path)
    }

    /// Locates the lockfile, preferring .ppm.lock then ppm.lock.
    pub fn locate(plugins_dir: &Path) -> PathBuf {
        let hidden = plugins_dir.join(LOCKFILE_NAME);
        if hidden.exists() {
            return hidden;
        }
        let visible = plugins_dir.join(LOCKFILE_FALLBACK);
        if visible.exists() {
            return visible;
        }
        hidden
    }

    /// Record or update a marketplace plugin in the lockfile.
    pub fn record_marketplace_plugin(&mut self, meta: &ExternalPluginMetadata, filename: &str) {
        let locked = LockedPlugin {
            id: meta.id,
            public_id: meta.public_id.clone(),
            name: meta.name.clone(),
            author: meta.dev_name.clone(),
            version: meta.version.clone(),
            file: filename.to_string(),
            updated_at: Some(meta.updated_at.clone()),
        };
        self.plugins.insert(meta.public_id.clone(), locked);
    }

    /// Remove a plugin entry by its public ID, name, or filename.
    pub fn remove_plugin(&mut self, query: &str) -> Option<LockedPlugin> {
        let trimmed = query.trim();
        // 1. Direct key match (public_id)
        if let Some(removed) = self.plugins.remove(trimmed) {
            return Some(removed);
        }
        // 2. Match by file or name or database ID
        let key_to_remove = self.plugins.iter().find_map(|(k, p)| {
            if p.file.eq_ignore_ascii_case(trimmed)
                || p.name.eq_ignore_ascii_case(trimmed)
                || p.id.to_string() == trimmed
                || p.file
                    .trim_end_matches(".wasm")
                    .eq_ignore_ascii_case(trimmed)
                || p.file
                    .trim_end_matches(".wasm.deactivated")
                    .eq_ignore_ascii_case(trimmed)
            {
                Some(k.clone())
            } else {
                None
            }
        });

        if let Some(key) = key_to_remove {
            self.plugins.remove(&key)
        } else {
            None
        }
    }

    /// Find a plugin by public ID, database ID, name, or filename.
    pub fn find_plugin(&self, query: &str) -> Option<&LockedPlugin> {
        let trimmed = query.trim();
        if let Some(p) = self.plugins.get(trimmed) {
            return Some(p);
        }
        self.plugins.values().find(|p| {
            p.public_id.eq_ignore_ascii_case(trimmed)
                || p.id.to_string() == trimmed
                || p.name.eq_ignore_ascii_case(trimmed)
                || p.file.eq_ignore_ascii_case(trimmed)
                || p.file
                    .trim_end_matches(".wasm")
                    .eq_ignore_ascii_case(trimmed)
                || p.file
                    .trim_end_matches(".wasm.deactivated")
                    .eq_ignore_ascii_case(trimmed)
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lockfile_roundtrip() {
        let mut lock = Lockfile::new();
        let meta = ExternalPluginMetadata {
            id: 42,
            public_id: "S1zisQxa".into(),
            name: "Economy".into(),
            dev_name: "alice".into(),
            version: Some("1.2.0".into()),
            category: Some("Economy".into()),
            type_: "free".into(),
            price: 0.0,
            downloads: 100,
            preview_url: None,
            created_at: "2026-01-01T00:00:00Z".into(),
            updated_at: "2026-10-06T15:00:00Z".into(),
        };

        lock.record_marketplace_plugin(&meta, "Economy.wasm");
        assert_eq!(lock.plugins.len(), 1);

        let serialized = toml::to_string(&lock).unwrap();
        let deserialized: Lockfile = toml::from_str(&serialized).unwrap();
        assert_eq!(lock, deserialized);

        let found = deserialized.find_plugin("S1zisQxa");
        assert!(found.is_some());
        assert_eq!(found.unwrap().name, "Economy");

        let found_by_name = deserialized.find_plugin("economy");
        assert!(found_by_name.is_some());

        let found_by_file = deserialized.find_plugin("Economy.wasm");
        assert!(found_by_file.is_some());
    }

    #[test]
    fn test_lockfile_remove() {
        let mut lock = Lockfile::new();
        let meta = ExternalPluginMetadata {
            id: 1,
            public_id: "pub_1".into(),
            name: "TestPlugin".into(),
            dev_name: "bob".into(),
            version: Some("0.1.0".into()),
            category: None,
            type_: "free".into(),
            price: 0.0,
            downloads: 10,
            preview_url: None,
            created_at: "".into(),
            updated_at: "".into(),
        };

        lock.record_marketplace_plugin(&meta, "TestPlugin.wasm");
        assert_eq!(lock.plugins.len(), 1);

        // Remove by filename
        assert!(lock.remove_plugin("TestPlugin.wasm").is_some());
        assert!(lock.plugins.is_empty());
    }
}
