// Copyright (C) 2026 Pumpkin-MC Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use super::TemplateContext;

pub fn generate(dir: &Path, ctx: &TemplateContext) -> Result<()> {
    fs::create_dir_all(dir.join("src"))?;
    fs::create_dir_all(dir.join(".cargo"))?;

    // Cargo.toml
    let cargo_toml = format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"
authors = ["{author}"]
description = "{desc}"

[lib]
crate-type = ["cdylib"]

[dependencies]
pumpkin-plugin-api = "0.1.0-dev"
tracing = "0.1"
"#,
        name = ctx.name,
        author = ctx.author,
        desc = ctx.description
    );
    fs::write(dir.join("Cargo.toml"), cargo_toml)
        .context("Failed to write Cargo.toml")?;

    // .cargo/config.toml
    let cargo_config = r#"[build]
target = "wasm32-wasip2"
"#;
    fs::write(dir.join(".cargo/config.toml"), cargo_config)
        .context("Failed to write .cargo/config.toml")?;

    // .gitignore
    let gitignore = r#"/target
**/*.rs.bk
*.wasm
"#;
    fs::write(dir.join(".gitignore"), gitignore)
        .context("Failed to write .gitignore")?;

    // src/lib.rs
    let struct_name = format!("{}Plugin", ctx.struct_name());
    let mut imports = vec![
        "Context".to_string(),
        "Plugin".to_string(),
        "PluginMetadata".to_string(),
        "register_plugin".to_string(),
    ];

    if ctx.include_command || ctx.include_event {
        imports.push("Server".to_string());
        imports.push("text::TextComponent".to_string());
    }

    let mut extra_imports = String::new();
    let mut handlers = String::new();
    let mut on_load_body = String::new();

    on_load_body.push_str(&format!(
        "        tracing::info!(\"{} plugin loaded successfully!\");\n",
        ctx.name
    ));

    if ctx.include_command {
        extra_imports.push_str(
            r#"use pumpkin_plugin_api::{
    command::{Command, CommandError, CommandSender, ConsumedArgs},
    commands::CommandHandler,
};
"#,
        );

        handlers.push_str(&format!(
            r#"/// Handles the '/{name}' custom command.
struct {cmd_struct};

impl CommandHandler for {cmd_struct} {{
    fn handle(
        &self,
        sender: CommandSender,
        _server: Server,
        _args: ConsumedArgs,
    ) -> Result<i32, CommandError> {{
        let sender_name = sender.get_name();
        sender.send_message(TextComponent::text(&format!(
            "Hello, {{sender_name}}! Greetings from {name} plugin."
        )));
        Ok(0)
    }}
}}
"#,
            name = ctx.name,
            cmd_struct = format!("{}CommandHandler", ctx.struct_name())
        ));

        on_load_body.push_str(&format!(
            r#"        // Register custom command '/{name}'
        let cmd = Command::new(&["{name}"], "A greeting command from {name}");
        context.register_command(cmd, {cmd_struct});
"#,
            name = ctx.name,
            cmd_struct = format!("{}CommandHandler", ctx.struct_name())
        ));
    }

    if ctx.include_event {
        extra_imports.push_str(
            r#"use pumpkin_plugin_api::{
    events::{EventHandler, player::PlayerJoinEvent},
    events_wit::PlayerJoinEventData,
};
"#,
        );

        handlers.push_str(&format!(
            r#"/// Listens for players joining the server.
struct JoinListener;

impl EventHandler<PlayerJoinEvent> for JoinListener {{
    fn handle(&self, _server: Server, event: PlayerJoinEventData) -> PlayerJoinEventData {{
        let name = event.player.get_name();
        tracing::info!("Player joined: {{name}}");

        event.player.send_system_message(
            TextComponent::text(&format!("Welcome to the server, {{name}}!")),
            false,
        );

        event
    }}
}}
"#
        ));

        on_load_body.push_str(
            r#"        // Register player join event handler
        context.register_event_handler(JoinListener);
"#,
        );
    }

    let lib_rs = format!(
        r#"//! # {name} Plugin for Pumpkin Minecraft Server
//!
//! Generated by `ppm` (Pumpkin Package Manager).

use pumpkin_plugin_api::{{{imports}}};
{extra_imports}
{handlers}
/// Main plugin struct for {name}.
pub struct {struct_name};

impl Plugin for {struct_name} {{
    fn new() -> Self {{
        {struct_name}
    }}

    fn metadata(&self) -> PluginMetadata {{
        PluginMetadata {{
            name: "{name}".into(),
            version: env!("CARGO_PKG_VERSION").into(),
            authors: vec!["{author}".into()],
            description: "{desc}".into(),
            dependencies: vec![],
            permissions: vec![],
        }}
    }}

    fn on_load(&self, context: Context) -> Result<(), String> {{
{on_load_body}        Ok(())
    }}

    fn on_unload(&self, _context: Context) -> Result<(), String> {{
        tracing::info!("{name} plugin unloaded.");
        Ok(())
    }}
}}

// Export plugin entrypoint
register_plugin!({struct_name});
"#,
        name = ctx.name,
        imports = imports.join(", "),
        extra_imports = extra_imports,
        handlers = handlers,
        struct_name = struct_name,
        author = ctx.author,
        desc = ctx.description,
        on_load_body = on_load_body
    );

    fs::write(dir.join("src/lib.rs"), lib_rs)
        .context("Failed to write src/lib.rs")?;

    // README.md
    let readme = format!(
        r#"# {name}

{desc}

A WebAssembly plugin for the [Pumpkin](https://github.com/Pumpkin-MC/Pumpkin) Minecraft server, written in Rust.

## Prerequisites

Ensure you have Rust and the WebAssembly WASI target installed:

```bash
rustup target add wasm32-wasip2
```

## Building

Build the `.wasm` plugin binary using Cargo:

```bash
cargo build --release
```

The compiled WebAssembly binary will be generated at:
```
target/wasm32-wasip2/release/{name_underscores}.wasm
```

## Installing to Pumpkin

Copy the resulting `.wasm` file into your Pumpkin server's `plugins/` directory:

```bash
cp target/wasm32-wasip2/release/{name_underscores}.wasm /path/to/pumpkin/plugins/
```

Or test with `ppm`:
```bash
ppm installed
```
"#,
        name = ctx.name,
        desc = ctx.description,
        name_underscores = ctx.name.replace('-', "_")
    );
    fs::write(dir.join("README.md"), readme)
        .context("Failed to write README.md")?;

    Ok(())
}
